OBMFULL-3321 relevant RPM and DEB packaging changes

diff --git a/java/sync/debian/obm-locator.postinst b/java/sync/debian/obm-locator.postinst
--- a/java/sync/debian/obm-locator.postinst
+++ b/java/sync/debian/obm-locator.postinst
@@ -59,7 +59,14 @@ rm -rf /var/lib/obm-locator/org.*
 if [ -d /var/log/obm-locator ]; then
   chown -R jetty:adm /var/log/obm-locator
 else 
-  echo "/var/log/obm-locator must exist"
+  echo "error : /var/log/obm-locator must exist."
+  exit 1
+fi
+
+if [ -d /var/lib/obm-locator ]; then
+  chown -R jetty:adm /var/log/obm-locator
+else
+  echo "error : /var/lib/obm-locator must exist."
   exit 1
 fi
 
